spring:
  application:
    name: myblog
  security:
    oauth2:
      client:
        registration:
          google:
            client_id: 453904110029-sjllaj2qpckr3n568l9ugfo8vck95ojb.apps.googleusercontent.com
            client_secret: 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
            scope:
              - email
              - profile


  # 데이터베이스 설정
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA 설정
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
    defer-datasource-initialization: true

# JWT 설정
jwt:
  issuer: dac05049@naver.com
  secret_key: study-springboot

